### PR TITLE
feat: add docker and php-cs-fixer

### PR DESCRIPTION
**Pull request by Trusted97**
Hi @whiteCcinn 😄 

In this PR I've added

- Dockerized containers with php version 8+
- Support for symfony 6.x
- PHP-CS-FIXER with a standard file instead of composer dependency

I've also launched `php-cs-fixer` for style the files 👍 

In the next PR once this will be merged i'll add Test and CI/CD 🚀

### CODE REVIEW

**Comment by whiteCcinn** [comment]
Sorry, due to the serious epidemic in China and personal work reasons, I failed to timely review, I will review later, thank you for your contribution @Trusted97

**Comment by Trusted97** [comment]
Hi @whiteCcinn,
I hope you are well, i can't wait for the review to start adding more features!

**Comment by whiteCcinn** [comment]
感谢你的贡献 @Trusted97

**Comment by whiteCcinn** [comment]
Thank you for your contribution @Trusted97

**Pull request merged**
